server:
  port: 8082
spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://localhost:3306/hammers?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8 #url
    username: root  #用户名
    password: root  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
  jpa:
    show-sql: true # 控制台打印SQL
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.greathammers.superhammer.entity #配置实体类